In [3]:
import numpy as np
X = np.array([[-2, -2], [-1, 4], [2, 3]])
# Ham tinh ma tran hiep phuong sai
C1 = np.cov(X.T)
print(C1)

[[ 4.33333333  3.83333333]
 [ 3.83333333 10.33333333]]


In [4]:
# ma tran chuyen vi
XT = X.T 
print(XT)

[[-2 -1  2]
 [-2  4  3]]


In [12]:
# tinh trung binh tren tung truc toa do
Mx = (-2 - 1 + 2) / 3
My = (-2 + 4 +3) / 3
M = np.array([[Mx, My], [Mx, My], [Mx, My]])
# do lech cua mau so voi trung binh mau
D = XT - M.T
print(D)

[[-1.66666667 -0.66666667  2.33333333]
 [-3.66666667  2.33333333  1.33333333]]


In [13]:
# ma tran hiep binh phuong : 1/(N-1) * D * D.T
Cov = (1/2) * np.dot(D ,D.T)
print(Cov)

[[ 4.33333333  3.83333333]
 [ 3.83333333 10.33333333]]
